import React, { useEffect, useState } from 'react'
import { StyleSheet, Text, View } from 'react-native'
import axios from 'axios'
import { URL } from '../constants/api'
import PlayerStack from '../navigation/articleStack'